// This file is part of tja.
//
// Copyright (c) 2026  René Coignard <contact@renecoignard.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use clap::{Parser, ValueEnum};
use rand::seq::IndexedRandom;

#[derive(Clone, Debug, ValueEnum)]
enum Lang {
    En,
    Ru,
}

#[derive(Parser, Debug)]
#[command(author, version, about = "Show random card from Oblique Strategies")]
struct Cli {
    #[arg(long, default_value = "en")]
    lang: Lang,
}

const CARDS_EN: &[&str] = &[
    "Remove specifics and convert to ambiguities",
    "Think of the radio",
    "Don't be frightened of clichés",
    "What is the reality of the situation?",
    "Are there sections? Consider transitions",
    "Turn it upside down",
    "Allow an easement\n(an easement is the abandonment of a stricture)",
    "Simple subtraction",
    "Go slowly all the way round the outside",
    "A line has two sides",
    "Infinitesimal gradations",
    "Make an exhaustive list of everything you might do\nand do the last thing on the list",
    "Into the impossible",
    "Ask people to work against their better judgment",
    "Take away the elements in order of apparent non-importance",
    "Change instrument roles",
    "Accretion",
    "Disconnect from desire",
    "Emphasize repetitions",
    "Don't be afraid of things because they're easy to do",
    "Is there something missing?",
    "Don't be frightened to display your talents",
    "Breathe more deeply",
    "Honor thy error as a hidden intention",
    "Only one element of each kind",
    "Use unqualified people",
    "How would you have done it?",
    "Emphasize differences",
    "Do nothing for as long as possible",
    "Bridges\n  — build\n  — burn",
    "Water",
    "You don't have to be ashamed of using your own ideas",
    "Tidy up",
    "Do the words need changing?",
    "Ask your body",
    "Make a sudden, destructive unpredictable action; incorporate",
    "Consult other sources",
    "Use an unacceptable color",
    "Humanize something free of error",
    "Use filters",
    "Balance the consistency principle with the inconsistency principle",
    "Fill every beat with something",
    "Discard an axiom",
    "What wouldn't you do?",
    "Decorate, decorate",
    "Listen to the quiet voice",
    "Is it finished?",
    "Put in earplugs",
    "Give the game away",
    "Reverse",
    "Abandon normal instruments",
    "Use fewer notes",
    "Repetition is a form of change",
    "Give way to your worst impulse",
    "Trust in the you of now",
    "What would your closest friend do?",
    "Distorting time",
    "Make a blank valuable by putting it in an exquisite frame",
    "The inconsistency principle",
    "Ghost echoes",
    "You can only make one dot at a time",
    "Just carry on",
    "(Organic) machinery",
    "Don't break the silence",
    "Discover the recipes you are using and abandon them",
    "Cascades",
    "Courage!",
    "What mistakes did you make last time?",
    "You are an engineer",
    "Consider different fading systems",
    "Mute and continue",
    "It is quite possible (after all)",
    "Don't stress one thing more than another",
    "Remove ambiguities and convert to specifics",
    "Look at the order in which you do things",
    "Go outside. Shut the door.",
    "Do we need holes?",
    "Cluster analysis",
    "Work at a different speed",
    "Do something boring",
    "Define an area as 'safe' and use it as an anchor",
    "Overtly resist change",
    "Accept advice",
    "Look closely at the most embarrassing details and amplify them",
    "Mechanicalize something idiosyncratic",
    "Emphasize the flaws",
    "Remember those quiet evenings",
    "Take a break",
    "The tape is now the music",
    "Short circuit\n(example: a man eating peas with the idea that they will\nimprove his virility shovels them straight into his lap)",
    "Use an old idea",
    "Destroy\n  — nothing\n  — the most important thing",
    "Change nothing and continue with immaculate consistency",
    "Imagine the music as a moving chain or caterpillar",
    "Intentions\n  — credibility of\n  — nobility of\n  — humility of",
    "Imagine the piece as a set of disconnected events",
    "What are you really thinking about just now?\nIncorporate.",
    "Children's voices\n  — speaking\n  — singing",
    "Assemble some of the instruments in a group and treat the group",
    "Shut the door and listen from outside",
    "Is the tuning appropriate?",
    "Look at a very small object, look at its centre",
    "Feedback recordings into an acoustic situation",
    "Towards the insignificant",
    "Simply a matter of work",
    "Not building a wall but making a brick",
    "Revaluation (a warm feeling)",
    "Disciplined self-indulgence",
    "The most important thing is the thing most easily forgotten",
    "Idiot glee",
    "Be extravagant",
    "State the problem in words as clearly as possible",
    "Always first steps",
    "Question the heroic approach",
    "Always give yourself credit for having more than personality",
    "Faced with a choice, do both",
    "Tape your mouth",
    "Twist the spine",
    "Get your neck massaged",
    "Do the washing up",
    "Convert a melodic element into a rhythmic element",
    "Spectrum analysis",
    "Lowest common denominator check\n  — single beat\n  — single note\n  — single riff",
    "Listen in total darkness,\nor in a very large room, very quietly",
    "Would anybody want it?",
    "Retrace your steps",
    "Go to an extreme, move back to a more comfortable place",
    "Once the search is in progress, something will be found",
    "Only a part, not the whole",
    "From nothing to more than nothing",
    "Be less critical more often",
];

const CARDS_RU: &[&str] = &[
    "Убери конкретику и переведи в неопределённость",
    "Думай о радио",
    "Не бойся клише",
    "Какова реальность ситуации?",
    "Есть ли разделы? Подумай о переходах",
    "Переверни вверх ногами",
    "Позволь себе послабление\n(послабление — это отказ от ограничения)",
    "Простое вычитание",
    "Медленно обойди всё по периметру",
    "У линии есть две стороны",
    "Бесконечно малые градации",
    "Составь исчерпывающий список всего, что ты мог бы сделать,\nи сделай последнее",
    "В невозможное",
    "Попроси людей действовать вопреки собственному благоразумию",
    "Убирай элементы в порядке кажущейся незначимости",
    "Поменяй роли инструментов",
    "Аккреция",
    "Отстранись от желания",
    "Подчёркивай повторения",
    "Не бойся делать вещи только потому, что они просты",
    "Чего-то не хватает?",
    "Не бойся проявлять свои таланты",
    "Дыши глубже",
    "Чти свою ошибку как скрытый замысел",
    "Только один элемент каждого вида",
    "Используй неквалифицированных людей",
    "Как бы ты это сделал?",
    "Подчёркивай различия",
    "Как можно дольше не делай ничего",
    "Мосты\n  — возводи\n  — сжигай",
    "Вода",
    "Не стыдись использовать собственные идеи",
    "Приведи в порядок",
    "Нужно ли менять слова?",
    "Спроси своё тело",
    "Соверши внезапное, разрушительное, непредсказуемое действие — и включи его",
    "Обратись к другим источникам",
    "Используй неприемлемый цвет",
    "Очеловечь то, что лишено ошибок",
    "Используй фильтры",
    "Уравновесь принцип последовательности принципом непоследовательности",
    "Заполни каждый удар чем-нибудь",
    "Откажись от аксиомы",
    "Чего бы ты не стал делать?",
    "Укрась, укрась",
    "Слушай тихий голос",
    "Это закончено?",
    "Вставь беруши",
    "Раскрой карты",
    "Обрати вспять",
    "Откажись от обычных инструментов",
    "Используй меньше нот",
    "Повторение — это форма изменения",
    "Поддайся своему худшему порыву",
    "Доверяй себе настоящему",
    "Что бы сделал твой лучший друг?",
    "Искажение времени",
    "Сделай пустоту ценной, поместив её в изысканную раму",
    "Принцип непоследовательности",
    "Призрачные эхо",
    "Ты можешь ставить только одну точку за раз",
    "Просто продолжай",
    "(Органическая) машинерия",
    "Не нарушай тишину",
    "Обнаружь рецепты, которыми пользуешься, и откажись от них",
    "Каскады",
    "Смелость!",
    "Какие ошибки ты допустил в прошлый раз?",
    "Ты инженер",
    "Рассмотри различные способы затухания",
    "Заглуши и продолжай",
    "Это вполне возможно (в конце концов)",
    "Не выделяй одно больше другого",
    "Убери неопределённость и переведи в конкретику",
    "Посмотри на порядок, в котором ты делаешь вещи",
    "Выйди на улицу. Закрой дверь.",
    "Нужны ли нам дыры?",
    "Кластерный анализ",
    "Работай в другом темпе",
    "Сделай что-нибудь скучное",
    "Определи область как «безопасную» и используй её как якорь",
    "Открыто сопротивляйся переменам",
    "Принимай советы",
    "Внимательно посмотри на самые неловкие детали и усиль их",
    "Механизируй что-то самобытное",
    "Подчёркивай недостатки",
    "Вспомни те тихие вечера",
    "Сделай перерыв",
    "Лента теперь и есть музыка",
    "Короткое замыкание\n(пример: человек ест горох, веря, что это улучшит его мужскую\nсилу, и сразу высыпает его себе на колени)",
    "Используй старую идею",
    "Уничтожь\n  — ничего\n  — самое важное",
    "Не меняй ничего и продолжай с безупречной последовательностью",
    "Представь музыку как движущуюся цепь или гусеницу",
    "Намерения\n  — их достоверность\n  — их благородство\n  — их смирение",
    "Представь произведение как набор несвязанных событий",
    "О чём ты на самом деле думаешь прямо сейчас?\nВключи это.",
    "Детские голоса\n  — говорящие\n  — поющие",
    "Собери несколько инструментов в группу и обрабатывай группу",
    "Закрой дверь и слушай снаружи",
    "Подходит ли строй?",
    "Рассмотри очень маленький объект, посмотри на его центр",
    "Пропусти записи обратно в акустическую ситуацию",
    "К незначительному",
    "Просто дело труда",
    "Не строить стену, а делать кирпич",
    "Переоценка (тёплое чувство)",
    "Дисциплинированное потакание себе",
    "Самое важное — это то, что легче всего забыть",
    "Идиотский восторг",
    "Будь экстравагантным",
    "Сформулируй проблему как можно чётче",
    "Всегда первые шаги",
    "Поставь под сомнение героический подход",
    "Всегда признавай за собой большее, чем просто личность",
    "Столкнувшись с выбором, сделай и то, и другое",
    "Заклей рот скотчем",
    "Скрути позвоночник",
    "Сделай массаж шеи",
    "Помой посуду",
    "Преврати мелодический элемент в ритмический",
    "Спектральный анализ",
    "Проверка наименьшего общего знаменателя\n  — один удар\n  — одна нота\n  — один рифф",
    "Слушай в полной темноте\nили в очень большом помещении, очень тихо",
    "Нужно ли это кому-нибудь?",
    "Вернись по своим следам",
    "Дойди до крайности, потом вернись в более комфортное место",
    "Если поиск начался, что-нибудь найдётся",
    "Только часть, не целое",
    "От ничего к чуть больше чем ничего",
    "Будь менее критичным почаще",
];

fn main() {
    let cli = Cli::parse();
    let cards = match cli.lang {
        Lang::En => CARDS_EN,
        Lang::Ru => CARDS_RU,
    };
    let mut rng = rand::rng();
    let card = cards.choose(&mut rng).expect("card list is non-empty");
    println!("{card}");
}
